// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.IO;


namespace testtask_deuscraft
{
	public class CheckSummEvaluator
	{
		BinaryReader BinaryReader;

		public CheckSummEvaluator (BinaryReader binaryReader)
		{
			BinaryReader = binaryReader;
		}

		public long EvaluateCheckSumm()
		{
			long checkSumm = 0;
 
			long length = BinaryReader.BaseStream.Length;
			int position = 0;
			while (position < length - 100)
			{
				int integerFromFile = BinaryReader.ReadInt32();
				checkSumm += integerFromFile;
				position += 4;
			}

			return checkSumm;
		}
	}
}

