// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.IO;
using System.Collections.Generic;
using System.Text;


namespace testtask_deuscraft
{
	public class FileStringSearcher
	{
		public static int NOT_FOUND = -1;

		String Content;
		String SearchString;

		Encoding Encoding;

		public FileStringSearcher (StreamReader targetFile, String searchString)
		{
			Content = targetFile.ReadToEnd ();
			SearchString = searchString;

			Encoding = targetFile.CurrentEncoding;
		}

		/// <summary>
		/// Получение множества с местами вхождений искомой строки в файл, в байтах
		/// </summary>
		/// <returns>The entry array.</returns>
		public SortedSet<int> GetSearchStringEntrySet()
		{
			SortedSet<int> entrySet = new SortedSet<int>();
			int currentIndex = 0;

			while (true) 
			{
				int entryIndex = Content.IndexOf(SearchString, currentIndex + 1);  // +1 = next symbol

				if (NOT_FOUND == entryIndex)
				{
					break;
				}

				String previousString = Content.Substring(0, entryIndex);
				int bytesCount = Encoding.GetByteCount(previousString);

				entrySet.Add(bytesCount);

				currentIndex = entryIndex;
			}

			return entrySet;
		}
	}
}